version: 2.1
orbs:
  node: circleci/node@4.7.0
  coveralls: coveralls/coveralls@1.0.4

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          name: "npm install"
          command: npm install

  test:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          name: "npm install"
          command: npm install
      - run:
          name: "npm test"
          command: npm test
      - run: # run code coverage report
          name: code-coverage
          command: npm coverage
      - coveralls/upload
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.repo_token}
